AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  EipAssigner:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: eip-assigner
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.13
      Architectures: [arm64]
      Timeout: 30
      Environment:
        Variables:
          ELASTIC_IP_ALLOCATION_ID: ""
